name: burt_network
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  logger: ^1.4.0
  meta: ^1.9.1
  protobuf: ^3.0.0

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
