name: rover
publish_to: none
environment:
  sdk: ^3.9.0

workspace:
  - arm_auxillary
  - autonomy
  - burt_network
  - subsystems
  - video

dependencies:
  pubspec_parse: ^1.5.0
  args: ^2.6.0
  dhttpd: ^4.1.0
  cli_spin: ^1.0.1
  burt_network: ^2.4.0

dev_dependencies:
  # dependency_validator: ^5.0.2
  very_good_analysis: ^6.0.0

# dependency_overrides:
#   ffigen:
#     git:
#       url: https://github.com/dart-lang/native
#       path: pkgs/ffigen
