name: burt_network
description: A starting point for Dart libraries or applications.
version: 2.7.0
publish_to: none
repository: https://github.com/BinghamtonRover/Networking

resolution: workspace
environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  coordinate_converter: ^1.2.3
  fixnum: ^1.1.1
  libserialport: ^0.3.0+1
  logger: ^2.0.2
  meta: ^1.9.1
  protobuf: ^6.0.0

dev_dependencies:
  test: ^1.21.0
