name: arm_auxillary
description: A sample command-line application.
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  burt_network: ^2.8.0
  collection: ^1.19.0
  subsystems: ^1.0.0
  video: ^1.1.0
  typed_isolate: ^6.0.0
  dartcv4: ^1.1.8

dev_dependencies:
  very_good_analysis: ^6.0.0
